### ISSUE TITLE
Ignore implicit methods and constructors when creating detections

### ISSUE THREAD

**Issue by lmove** [alien-tools/maracas#18]
Detections associated with implicit methods and constructors are being reported by Maracas. This causes some tests to fail in the `rest` project. After diving into this issue I found that Spoon reports that a constructor is explicit (i.e. the `implicit` attribute is set to `false`) even when it is clearly not defined in the class. I already tried using `getPosition().isValid()` but it didn't work as expected. We need to find a workaround for this issue.

**Comment by tdegueul** [comment]
Not commenting on the issue per se, but `rest` shouldn't be the one complaining first about this issue. `core` tests should have caught that right away (but there's basically none atm ;)

**Comment by lmove** [comment]
Check [issue 4348](https://github.com/INRIA/spoon/issues/4348) in the Spoon repository.
