### ISSUE TITLE
No compiler message when invoking a method that is static

### ISSUE THREAD

**Issue by lmove** [alien-tools/maracas#34]
The Maven compiler does not report an error when invoking a no longer static method in a static fashion. The broken use is correctly reported but there is no matching compiler message (true positives reported as false positives). The error is reported by the JDT compiler though.

Related broken use:
```
Path: path-to/maracas/test-data/comp-changes/client/src/mainclient/methodNoLongerStatic/MethodNoLongerStaticImp.java
Line: 5
Breaking change: METHOD_NOW_ABSTRACT
API use: IMPLEMENTS
Used declaration: main.methodNoLongerStatic.IMethodNoLongerStatic
Source declaration: methodNoLongerStatic()

Path: path-to/maracas/test-data/comp-changes/client/src/mainclient/methodNoLongerStatic/MethodNoLongerStaticImp.java
Line: 8
Breaking change: METHOD_NOW_ABSTRACT
API use: METHOD_INVOCATION
Used declaration: methodNoLongerStatic()
Source declaration: methodNoLongerStatic()
```

**Comment by lmove** [comment]
Using `-Xlint:static` option when compiling the source code with the Maven compiler.

**Comment by lmove** [comment]
This issue is actually related to the way we are filtering the compiler messages. We need to also filter broken uses, so for each package related to a breaking change, we only keep broken uses with such breaking change as part of its definition. For instance, in the `methodNoLongerStatic` package we report `METHOD_NOW_ABSTRACT` broken uses. We should limit ourselves to report `METHOD_NO_LONGER_STATIC` broken uses in such case. Te rest must be filtered out.

**Comment by tdegueul** [comment]
> This issue is actually related to the way we are filtering the compiler messages. We need to also filter broken uses, so for each package related to a breaking change, we only keep broken uses with such breaking change as part of its definition. For instance, in the `methodNoLongerStatic` package we report `METHOD_NOW_ABSTRACT` broken uses. We should limit ourselves to report `METHOD_NO_LONGER_STATIC` broken uses in such case. The rest must be filtered out.

Yes! That's what we do in our tests, with one little twist: the `noMoreChanges` test that counts the total number of broken uses per BCs accounts for all instances in all packages.
