### ISSUE TITLE
Point to the diff location instead of v1 location

### ISSUE THREAD

**Issue by lmove** [alien-tools/maracas#6]
JSON reports: BCs should point to the location in the diff that triggers it, not in v1. But is it always possible?

**Comment by tdegueul** [comment]
Solved in https://github.com/alien-tools/maracas/commit/9548e9a258af67ec2bb2f606bf8c46b73105b94b and https://github.com/break-bot/breakbot/commit/e90ed18e682871bb034fcd2e45ec1b25664bdf37.
